"""removed unused entity table

Revision ID: 2463c3811427
Revises: 4a82b60c36c1
Create Date: 2025-09-27 20:48:33.930406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2463c3811427'
down_revision: Union[str, Sequence[str], None] = '4a82b60c36c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('Key', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('Field', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('Type', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('Key'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
